### ISSUE TITLE
Slackのスラッシュコマンド調査

### ISSUE THREAD

**Issue by nasat75** [nasat75/time-liner#2]
### 概要
- スラッシュコマンドから始まる使い方を想定
- @taichi0514 にスラッシュコマンドのサンプル調査を依頼

### メモ
- to: @taichi0514 
- 何かtips等あれば追記おなしゃす

**Comment by taichi0514** [comment]
## 仕様1
/[command名] (引数)
引数でcommandの処理を分岐できるので
/emoji category
↑みたいな使い方が可能
/emoji anime
↑レスポンス :remu: :emiriya: 等のbotメッセージの表示が可能


## 仕様2
/emoji
↑のcommandを使用した際に
登録されたカテゴリーを出しそのリンクを押すと絵文字を登録しているwebサイトに飛ばす
↑ださい

**Comment by taichi0514** [comment]
https://api.slack.com/block-kit/surfaces/modals
block-kitもみたけどやっぱりslackの仕様に絵文字選択をカスタムで出す方法はないっぽいね

仕様1が妥当かも

**Comment by taichi0514** [comment]
@nasat75
